# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Imager-Filter-Sepia
version:      0.01
version_from: lib/Imager/Filter/Sepia.pm
installdirs:  site
requires:
    Imager:                        0.54
    Test::More:                    0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
